export const TileSize = 55;

export enum MoveDirection {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFT = "TURNLEFT",
  TURNRIGHT = "TURNRIGHT"
}

export enum PlayerState {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFTTOP = "TURNLEFTTOP",
  TURNLEFTLEFT = "TURNLEFTLEFT",
  TURNLEFTBOTTOM = "TURNLEFTBOTTOM",
  TURNLEFTRIGHT = "TURNLEFTRIGHT",
  TURNRIGHTTOP = "TURNRIGHTTOP",
  TURNRIGHTRIGHT = "TURNRIGHTRIGHT",
  TURNRIGHTBOTTOM = "TURNRIGHTBOTTOM",
  TURNRIGHTLEFT = "TURNRIGHTLEFT"
}

export enum TileType {
  WALL_ROW = "WALL_ROW",
  WALL_COLUMN = "WALL_COLUMN",
  WALL_LEFT_TOP = "WALL_LEFT_TOP",
  WALL_RIGHT_TOP = "WALL_RIGHT_TOP",
  WALL_LEFT_BOTTOM = "WALL_LEFT_BOTTOM",
  WALL_RIGHT_BOTTOM = "WALL_RIGHT_BOTTOM",
  CLIFF_LEFT = "CLIFF_ROW_START",
  CLIFF_CENTER = "CLIFF_ROW_CENTER",
  CLIFF_RIGHT = "CLIFF_ROW_END",
  FLOOR = "FLOOR"
}
