export enum MoveDirection {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFT = "TURNLEFT",
  TURNRIGHT = "TURNRIGHT"
}

export enum PlayerState {
  TOP = "TOP",
  BOTTOM = "BOTTOM",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  TURNLEFTTOP = "TURNLEFTTOP",
  TURNLEFTLEFT = "TURNLEFTLEFT",
  TURNLEFTBOTTOM = "TURNLEFTBOTTOM",
  TURNLEFTRIGHT = "TURNLEFTRIGHT",
  TURNRIGHTTOP = "TURNRIGHTTOP",
  TURNRIGHTRIGHT = "TURNRIGHTRIGHT",
  TURNRIGHTBOTTOM = "TURNRIGHTBOTTOM",
  TURNRIGHTLEFT = "TURNRIGHTLEFT"
}
